cmake_minimum_required(VERSION 3.20)
include(project/mhc.cmake)

if (WIN32)
    add_library(mhc_ucontext STATIC private/ucontext/mh_context.t.h source/ucontext/mh_context.c private/ucontext/win32_ucontext.h source/ucontext/win32_ucontext.c)
else()
    add_library(mhc_ucontext STATIC private/ucontext/mh_context.t.h source/ucontext/mh_context.c)
endif()
mhc_module_declare(ucontext)
mhc_feature(context ucontext/mh_context.t.h)